In [1]:
import pandas as pd

In [4]:
videogames = pd.read_csv(r"C:\Users\fnaje\OneDrive\Documents\UniAndes\3er Seminario\Proyecto_Clase_Videojuegos\data\games_clean.csv")

In [5]:
videogames.info()

<class 'pandas.DataFrame'>
RangeIndex: 8296 entries, 0 to 8295
Data columns (total 14 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   videogame_names            8296 non-null   str
 1   platform                   8296 non-null   str
 2   year_of_release            8296 non-null   int64
 3   genre                      8296 non-null   str
 4   na_sales                   8296 non-null   float64
 5   eu_sales                   8296 non-null   float64
 6   jp_sales                   8296 non-null   float64
 7   other_sales                8296 non-null   float64
 8   critic_score               8296 non-null   float64
 9   user_score                 8296 non-null   float64
 10  rating_esrb                8296 non-null   str
 11  total_sales                8296 non-null   float64
 12  gen_platform               8296 non-null   str
 13  classification_user_score  8296 non-null   str
dtypes: float64(7), int64(1), str(6)
memory usage: 1.2 MB

In [6]:
videogames.head()

,videogame_names,platform,year_of_release,genre,na_sales,eu_sales,jp_sales,other_sales,critic_score,user_score,rating_esrb,total_sales,gen_platform,classification_user_score
0,Wii Sports,Wii,2006,Sports,41.36,28.96,3.77,8.45,76.0,8.0,E,82.54,7ª Gen,Good
1,Mario Kart Wii,Wii,2008,Racing,15.68,12.76,3.79,3.29,82.0,8.3,E,35.52,7ª Gen,Good
2,Wii Sports Resort,Wii,2009,Sports,15.61,10.93,3.28,2.95,80.0,8.0,E,32.77,7ª Gen,Good
3,New Super Mario Bros.,DS,2006,Platform,11.28,9.14,6.50,2.88,89.0,8.5,E,29.80,7ª Gen,Excellent
4,Wii Play,Wii,2006,Misc,13.96,9.18,2.93,2.84,58.0,6.6,E,28.91,7ª Gen,Regular

In [10]:
videogames.groupby("year_of_release")["total_sales"].sum()

year_of_release
1980      1.05
1981      0.93
1982      0.62
1985      1.07
1988      0.03
1989      4.17
1990      1.40
1991     12.11
1992      7.91
1994     23.56
1995      5.45
1996     22.34
1997     50.13
1998     52.24
1999     56.72
2000     92.85
2001    268.92
2002    312.10
2003    284.46
2004    340.45
2005    355.71
2006    429.47
2007    481.19
2008    534.52
2009    497.67
2010    449.85
2011    404.55
2012    313.08
2013    299.97
2014    262.52
2015    192.56
2016    100.92
Name: total_sales, dtype: float64

In [9]:
videogames.groupby("year_of_release")["total_sales"].sum().idxmax()

np.int64(2008)

In [27]:
videogames.columns

Index(['videogame_names', 'platform', 'year_of_release', 'genre', 'na_sales',
       'eu_sales', 'jp_sales', 'other_sales', 'critic_score', 'user_score',
       'rating_esrb', 'total_sales', 'gen_platform',
       'classification_user_score'],
      dtype='str')

In [32]:
videogames[(videogames["year_of_release"] >= 1987) & (videogames["year_of_release"] <= 2009) & (videogames["platform"].isin(["Xbox", "Wii"]))]

,videogame_names,platform,year_of_release,genre,na_sales,eu_sales,jp_sales,other_sales,critic_score,user_score,rating_esrb,total_sales,gen_platform,classification_user_score
0,Wii Sports,Wii,2006,Sports,41.36,28.96,3.77,8.45,76.0,8.0,E,82.54,7ª Gen,Good
1,Mario Kart Wii,Wii,2008,Racing,15.68,12.76,3.79,3.29,82.0,8.3,E,35.52,7ª Gen,Good
2,Wii Sports Resort,Wii,2009,Sports,15.61,10.93,3.28,2.95,80.0,8.0,E,32.77,7ª Gen,Good
4,Wii Play,Wii,2006,Misc,13.96,9.18,2.93,2.84,58.0,6.6,E,28.91,7ª Gen,Regular
5,New Super Mario Bros. Wii,Wii,2009,Platform,14.44,6.94,4.70,2.24,87.0,8.4,E,28.32,7ª Gen,Good
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7961,Balls of Fury,Wii,2007,Sports,0.02,0.00,0.00,0.00,19.0,2.8,E10+,0.02,7ª Gen,Bad
8055,Emergency Mayhem,Wii,2008,Racing,0.02,0.00,0.00,0.00,40.0,4.3,T,0.02,7ª Gen,Bad
8145,Donkey Kong Jungle Beat,Wii,2008,Platform,0.00,0.01,0.00,0.00,80.0,8.3,RP,0.01,7ª Gen,Good
8199,Groovin' Blocks,Wii,2009,Puzzle,0.01,0.00,0.00,0.00,75.0,8.5,E,0.01,7ª Gen,Excellent
8272,Bomberman,Wii,2008,Puzzle,0.00,0.00,0.01,0.00,74.0,7.0,RP,0.01,7ª Gen,Good

In [33]:
videogames.groupby(["year_of_release", "genre"])["total_sales"].sum().reset_index()

     year_of_release         genre  total_sales
0               1980          Misc         1.05
1               1981        Action         0.93
2               1982       Shooter         0.62
3               1985        Puzzle         1.03
4               1985    Simulation         0.04
..               ...           ...          ...
268             2016  Role-Playing         7.48
269             2016       Shooter        35.24
270             2016    Simulation         1.50
271             2016        Sports        22.92
272             2016      Strategy         0.88

[273 rows x 3 columns]

In [34]:
videogames.groupby("genre")["total_sales"].sum().nlargest(3).index.to_list()

['Action', 'Sports', 'Shooter']